### ISSUE TITLE
General Issues

### ISSUE THREAD

**Issue by shpoongle** [boxdot/gurk-rs#184]
Hello,

I've been using Gurk for a while now. It really is beyond fantastic. However I have some recurring issues.

1) Messages that are read in Gurk are not showing as read to person who sent them
2) Messages don't send, this happens erratically after some time of use and can't be corrected even with a complete removal and full re-install. Restarting Gurk 24/48 hours later seems to fix it - sometimes, but not always.
3) Gurk Quits randomly.

This happens when using both pre-compiled packages and installing from cargo.

System being used is : Devuan Linux - Testing 

Not sure if this could be related to system time? VPN use on both machine where Gurk is installed and on Linked device? Or some other reason.

All other functionality in Gurk works fantastically and as previously mentioned is one of the best and most useful pieces of software even written. But these issues force the constant return to Signal-Desktop.

Any help would be appreciated.

Thanks :)

**Comment by boxdot** [comment]
Thank you for reporting the issues (and kind words).

Maybe we can solve the issues one by one.

3 sounds like the most several one. If you run gurk with `gurk -v` it will log into a file `gurk.log` in the current directory. Whenever it quits randomly, you should be able to see a panic stacktrace there. It would be fantastic, if you could send us this backtrace.

Could it be that 2 happens when there is no internet connection? We did not implement a retry and silently eat the error. This is actually a very bad UX, and we definitely should fix it.

I am not entirely sure about fhe issue 1. I remember that some work was done there. But it might be that it is not fully implemented. I have to double check.

**Comment by shpoongle** [comment]
Sorry for the delay in reply. But I was waiting for a random quit and the good news is that on the latest binary release I have not had any random quits :))))

However, the other problems persist.

To summarise:

Messages (including attachments) send back and forth to multiple  contacts in list without any issue other than the receiver not 
being notified of messages received by Gurk as being 'read'.

It should be noted however that on the linked device, received messages that have been read on Gurk are not shown as read until opened.

At some point. Seemingly at random, though notably at around a few days of use sending messages from Gurk will fail.

Receiving messages still works.

All connectivity during this time is constant, no drops in connection.

Whereas it has been possible to get messages to send again after a period of time, typically a few days. This is no longer working.

What I do notice though is that the date is incorrect. For example

I attempted to send today (Monday 10th October 2022)

However the date on the timestamp of the message shown on Gurk marks  it as Saturday.

output of 'date' is Mon Oct 10 01:08:37 PM EEST 2022

output of 'date -u' Mon Oct 10 10:08:40 AM UTC 2022

output of 'hwclock' is: 2022-10-10 13:08:51.373998+03:00

All are accurate.

So its possible that this is a chrono related issue?

Thanks

**Comment by shpoongle** [comment]
I just noticed that date -u is actually incorrect, the date is correct but the time is not.
